name: CI

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: '12'
      - uses: actions/cache@v2.1.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: npm run build
      - run: touch out/.nojekyll
      - run: cp CNAME out/CNAME
      - if: success()
        uses: crazy-max/ghaction-github-pages@v2.1.1
        with:
          target_branch: master
          build_dir: out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
